# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  nvidia-offload = pkgs.writeShellScriptBin "nvidia-offload" ''
    export __NV_PRIME_RENDER_OFFLOAD=1
    export __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
    export __GLX_VENDOR_LIBRARY_NAME=nvidia
    export __VK_LAYER_NV_optimus=NVIDIA_only
    exec "$@"
  '';
in

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  # boot.initrd.kernelModules = [ "nvidia" "nvidia_modeset" "nvidia_drm" ]; # "nvidia-uvm" removed
  # boot.kernelParams = [ "nvidia-drm.modeset=1" ];
  # boot.kernelModules = [ "kvm-amd" "nvidia" "nvidia_modeset" "nvidia_drm" ]; # "nvidia-uvm" removed
  # boot.blacklistedKernelModules = [ "nouveau" ];
  # boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/15250841-99ad-4c3c-9088-92b93fd76dbc";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-9126ff1a-ed71-4caf-a770-7056054e3b52".device = "/dev/disk/by-uuid/9126ff1a-ed71-4caf-a770-7056054e3b52";

  fileSystems."/boot/efi" =
    {
      device = "/dev/disk/by-uuid/600F-4616";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  #hardware = {
  #  opengl.enable = true;
  #  nvidia = {
  #    modesetting.enable = true;
  #    prime = {
  #      sync.enable = true;
  #    };
  #  };
  #};

  #hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.stable;
}
